// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handlers

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson44a4a3abDecodeGithubComGoParkMailRu20182LSPGAMEWebserverHandlers(in *jlexer.Lexer, out *responseGameRoom) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "hash":
			out.Hash = string(in.String())
		case "players":
			out.Players = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson44a4a3abEncodeGithubComGoParkMailRu20182LSPGAMEWebserverHandlers(out *jwriter.Writer, in responseGameRoom) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"hash\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Hash))
	}
	{
		const prefix string = ",\"players\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Players))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v responseGameRoom) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson44a4a3abEncodeGithubComGoParkMailRu20182LSPGAMEWebserverHandlers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v responseGameRoom) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson44a4a3abEncodeGithubComGoParkMailRu20182LSPGAMEWebserverHandlers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *responseGameRoom) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson44a4a3abDecodeGithubComGoParkMailRu20182LSPGAMEWebserverHandlers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *responseGameRoom) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson44a4a3abDecodeGithubComGoParkMailRu20182LSPGAMEWebserverHandlers(l, v)
}
